# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ms1JhoNElShMbAP3JALvs--tQQMW457U
"""

import streamlit as st
import numpy as np
from PIL import Image, ImageOps
from tensorflow.keras.models import load_model

model=load_model('digit_recognition_model.keras')

# 1. Define the uploaded_file variable using Streamlit's file uploader
uploaded_file = st.file_uploader("Upload a cheque image", type=["jpg", "jpeg", "png"])

# 2. Check if a file has been uploaded before processing
if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("L")
    image = ImageOps.invert(image)
    image = image.resize((28, 28))

    st.image(image, caption="Processed image", width=150)
    img = np.array(image) / 255.0
    img = img.reshape(1, 28, 28, 1)

    prediction = model.predict(img)
    digit = np.argmax(prediction)

    st.success(f"Predicted digit: {digit}")